### ISSUE TITLE
v2 Android Task List

### ISSUE THREAD

**Issue by Noitidart** [Noitidart/Enter-The-Gunbook#1]
* [x] For `<StatRow>` rather then `isValueNumeric` switch to `areMostValuesNumeric`
  * [x] Show the bar, but fill it with question marks if null
    * [x] Show string if string
* [x] Don't do "has more stuff" for now, instead just icon at top which launches wiki in browser
* [x] Sorting cards
* [x] Close card gui
* [x] For now, hide fabs while focus is in `TextInput`
* Support page
  * [x] Support link and reasoning (server cost support - [https://www.paypal.me/Noitidart](https://www.paypal.me/Noitidart))
* Social
  * [x] Thumbs up/down `ENTITYS.GUN` or `ENTITYS.ITEM` `kind`'s with count in header
  * [x] Add comment
    * [x] If username not set, gui for this
      * [x] Allow setting username in settings page
  * [x] Delete comment (if within 5 minutes)
  * [x] Mark comment helpful
  * [x] Sort comments by helpful or most recent
